import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import NextAuthProvider from '@/providers/NextAuthProvider';
import ReactQuery from '@/providers/ReactQueryProvider';
import { ContextProvider } from '@/providers/contextProvider';
import NextUIProvider from '@/providers/NextUIProvider';
import { Toaster } from 'react-hot-toast';
// const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
});
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${roboto.className} w-screen`}>
				<NextAuthProvider>
					<ReactQuery>
						<ContextProvider>
							<NextUIProvider>
								<Toaster
									position='top-right'
									reverseOrder={false}
									toastOptions={{
										duration: 6000,
										style: {
											borderRadius: '8px',
											background: '#333',
											color: '#fff',
										},
									}}
								/>
								{children}
							</NextUIProvider>
						</ContextProvider>
					</ReactQuery>
				</NextAuthProvider>
			</body>
		</html>
	);
}
