export const properties = [
	{
		id: 1,
		type: 'Apartment',
		name: 'Luxury Apartment',
		address: '123 Main St, Cityville',
		about_location: 'A beautiful apartment in the heart of the city.',
		general_information:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
		annual_rent_fee: 24000,
		comission_fee: 5,
		agency_fee: 2000,
		agreement_fee: 1000,
		total_fee: 27000,
		house_features: ['Swimming Pool', 'Gym', 'Parking', '24/7 Security'],
		extra_benefits: [
			'Free Wi-Fi',
			'Cable TV',
			'Housekeeping',
			'Laundry Service',
		],
		images: [
			'/images/property1.jpg',
			'/images/property2.jpg',
			'/images/property3.jpg',
		],
		agent_id: 1,
		landlord_id: 1,
	},
	{
		id: 2,
		type: 'House',
		name: 'Cozy Family House',
		address: '456 Elm St, Townsville',
		about_location: 'A cozy house perfect for families.',
		general_information: '3 bedrooms, 2 bathrooms, 1500 sqft',
		annual_rent_fee: 30000,
		comission_fee: 5,
		agency_fee: 2500,
		agreement_fee: 1500,
		total_fee: 36000,
		house_features: ['Garden', 'Garage', 'Fireplace'],
		extra_benefits: [
			'Free Wi-Fi',
			'Cable TV',
			'Housekeeping',
			'Laundry Service',
		],
		images: [
			'/images/property4.jpg',
			'/images/property5.jpg',
			'/images/property6.jpg',
		],
		agent_id: 2,
		landlord_id: 2,
	},
];

export const property = {
	id: 1,
	type: 'Apartment',
	name: 'Luxury Apartment',
	country: 'Nigeria',
	state: 'Kogi',
	city: 'Lokoja',
	address: '123 Main St, Cityville',
	about_location: 'A beautiful apartment in the heart of the city.',
	general_information:
		"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
	annual_rent_fee: 24000,
	comission_fee: 5,
	agency_fee: 2000,
	agreement_fee: 1000,
	total_fee: 27000,
	house_features: ['Swimming Pool', 'Gym', 'Parking', '24/7 Security'],
	extra_benefits: [
		'Free Wi-Fi',
		'Cable TV',
		'Housekeeping',
		'Laundry Service',
		'Free Wi-Fi',
		'Free Parking',
		'Free Breakfast',
		'3 toilet',
		'4 bedroom',
		'Car parking space',
		'Swimming pool',
		'Solar light',
		'Gate',
		'Security',
		'Fenced',
	],
	images: [
		'/images/property1.jpg',
		'/images/property2.jpg',
		'/images/property3.jpg',
	],
	agent_id: 1,
	landlord_id: 1,
	agent: {
		id: 1,
		name: 'John Doe',
		email: '',
		phone: '123-456-7890',
		profile_picture: '/images/agent.png',
		bio: "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
	},
	landlord: {
		id: 1,
		name: 'Jane Smith',
		email: '',
		phone: '987-654-3210',
		profile_picture: '/images/landlord1.jpg',
	},
	inspection_date: '2023-10-01',
	inspection_time: '10:00 AM',
};

export const reviews = [
	{
		id: 1,
		user: {
			id: 1,
			name: 'Alice Johnson',
			profile_picture: '/images/agent.png',
		},
		rating: 4.5,
		date: '2023-09-15',
		comment:
			'This apartment is amazing! The location is perfect and the amenities are top-notch.',
	},
	{
		id: 2,
		user: {
			id: 2,
			name: 'Bob Smith',
			profile_picture: '/images/agent.png',
		},
		rating: 4.0,
		date: '2023-09-20',
		comment:
			'I had a great experience with the landlord. The apartment was clean and well-maintained.',
	},
	{
		id: 3,
		user: {
			id: 3,
			name: 'Charlie Brown',
			profile_picture: '/images/agent.png',
		},
		rating: 5.0,
		date: '2023-09-25',
		comment:
			'Highly recommend this place! The amenities are fantastic and the staff is very helpful.',
	},
];
